<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<IsPackable>false</IsPackable>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
<PackageReference Include="xunit.v3" Version="4.0.0" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
<PackageReference Include="Microsoft.Data.Sqlite" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Markd.Core\Markd.Core.csproj" />
  </ItemGroup>

</Project>
